version: "3"
services:

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.1.0
    volumes:
       - ./elasticsearch/data:/usr/share/elasticsearch/data/
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.watermark.high=98%
      - cluster.routing.allocation.disk.watermark.flood_stage=98%
      - "ES_JAVA_OPTS=-Xmx512m -Xms256m"
      # ELASTIC_PASSWORD: changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - renat

  logstash:
    container_name: logstash
    image: logstash:7.1.0
    volumes:
#      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - renat
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: kibana:7.1.0
#    volumes:
#      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
#    environment:
#      ELASTICSEARCH_URL: "http://es:9200"
    networks:
      - renat
    depends_on:
      - elasticsearch

networks:
  renat:
    driver: bridge
